# Generated by Django 4.2.8 on 2024-01-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardiograf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kardiografUser',
        ),
    ]
