# Generated by Django 4.2.8 on 2024-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardiograf', '0004_kardiografuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardiografuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
    ]
