# Generated by Django 4.2.8 on 2024-01-13 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kardiograf', '0005_alter_kardiografuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardiografuser',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardiografuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
