# Generated by Django 4.2.8 on 2024-01-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardiograf', '0006_alter_kardiografuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardiografuser',
            name='numberPhone',
            field=models.TextField(blank=True),
        ),
    ]
