# Generated by Django 4.2.8 on 2024-01-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardiograf', '0008_kardiografuser_imageuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardiografuser',
            name='imageUser',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
