# Generated by Django 4.2.8 on 2024-01-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardiograf', '0009_alter_kardiografuser_imageuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardiografuser',
            name='numberPhone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
