# Generated by Django 5.0.2 on 2024-04-06 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardiograf', '0012_heartratedata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EKGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lead1', models.FloatField()),
                ('data_lead2', models.FloatField()),
                ('data_lead3', models.FloatField()),
                ('data_leadAVR', models.FloatField()),
                ('data_leadAVL', models.FloatField()),
                ('data_leadAVF', models.FloatField()),
                ('bpm', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
