# Generated by Django 5.0.2 on 2024-04-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardiograf', '0015_perhitungan'),
    ]

    operations = [
    ]
