# Generated by Django 5.0.2 on 2024-04-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kardiograf', '0016_auto_20240407_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EKGData',
        ),
    ]
